_target_: src.models.pred_module.PredModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.75
  patience: 10

model:
  _target_: src.models.components.eczemanet.EczemaNet
  num_classes: 4
  dropout: 0.5
  ordinal: ${ordinal}

monitor: "val/loss"

ordinal: True

n_classes: 4

crop: ${crop}