_target_: src.models.roi_module.FasterRCNNModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.75
  patience: 10

model:
  _target_: src.models.roi_module.get_faster_rcnn_resnet
  num_classes: 2
  backbone_name: "resnet50"
  anchor_size: ((32, 64, 128, 256, 512),)
  aspect_ratios: ((0.5, 1.0, 2.0),)
  fpn: True
  min_size: 600
  max_size: 1024

monitor: "val/loss"

auto_crop: False