_target_: src.models.seg_module.SegModule

optimizer:
#  _target_: torch.optim.SGD
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
#  momentum: 0.9
#  weight_decay: 0.005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.3
  patience: 5

monitor: "val/loss"

auto_crop: False

encoder_name: efficientnet_b3